config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :skills do
    collection do
      get :search
    end
  end
  resources :candidates
  resources :vacancies

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  include SkillSupport

  validates :name, format: {with: /\A\s*\p{Cyrillic}+\s+\p{Cyrillic}+\s+\p{Cyrillic}+\s*\z/, message: 'должно содержать 3 слова и только кириллические буквы и пробелы'}
  validates :salary, numericality: {greater_than: 0}
  validate :check_contacts_field

  scope :by_skill, ->(skill_id) {where("(array_remove(skill_ids, NULL) <> '{}') and (intset(?) && array_remove(skill_ids, NULL))", skill_id)}
  scope :by_skills, ->(skill_ids) {where("array_remove(skill_ids, NULL) <> '{}' and (icount(ARRAY[?] - array_remove(skill_ids, NULL)) = 0)", skill_ids)}
  #scope :by_any_skills, ->(skill_ids) {where("icount(ARRAY[?] & skill_ids) > 0", skill_ids)}
  scope :by_salary, -> {order :salary}
  scope :active, -> {where(is_active: true)}


  def check_contacts_field
    unless self.contacts.present?
      self.errors.add(:contacts, 'должны быть заданы') 
    else
      cnt = self.contacts || ''
      cnt.gsub!(/\s/, '')
      unless cnt =~ /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/  # мыло
        phone = cnt.gsub(/\s|-|_|\(|\)/, '')
        unless phone =~ /\A\+?\d*\z/
          self.errors.add(:contacts, 'должны быть представлены телефоном или адресом электронной почты')
        end
      end
    end
  end

  def skills
    Skill.where(id: self.skill_ids)
  end

  def best_vacancies
    skills = self.skill_ids.compact
    skills = [0] if !skills || skills.empty? 
    Vacancy.by_skills(skills).by_wage.active
  end

  def other_vacancies
    skills = self.skill_ids.compact
    skills = [0] if !skills || skills.empty?     
    Vacancy.active.
      select("vacancies.*, count(skills.id) common_skill_count, string_agg(skills.name, ', ') skill_names").
      joins("inner join skills on skills.id = ANY(array_remove(skill_ids, NULL) & ARRAY#{skills})").group('vacancies.id').
      having("count(skills.id) between 1 and icount(array_remove(skill_ids, NULL))-1").order('count(skills.id) desc').by_wage
  end

end

app/models/concerns/skill_support.rb
module SkillSupport
  extend ActiveSupport::Concern

  included do
    validate :check_skills
    before_save :build_skills

    attr_reader :new_skills
  end

  def new_skills= skills
    @new_skills = skills.select {|a| a.present?}
  end  

  def build_skills
    if @new_skills && @new_skills.any?
      @new_skills.each do |name|
        begin
          new_skill = Skill.create!(name: name)
          self.skill_ids += [new_skill.id]
        rescue ActiveRecord::RecordInvalid
          skill_id = Skill.like_name(name).first.try(:id)
          self.skill_ids |= [skill_id]
        end
      end
    end
    self.skill_ids.compact!
  end

  def check_skills
    skills = self.skill_ids.compact
    new_skills = @new_skills || []
    if skills.empty? && new_skills.empty?
      self.errors.add(:base, 'Навыки должны быть заданы')
    end
  end

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  scope :like_name, ->(name) {where("lower(name) like lower('%' || ? || '%')", name)}
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  include SkillSupport

  validates :name, :contacts, presence: true
  validates :wage, numericality: {greater_than: 0}

  scope :by_skill, ->(skill_id) {where("(array_remove(skill_ids, NULL) <> '{}') and (intset(?) && array_remove(skill_ids, NULL))", skill_id)}
  scope :by_skills, ->(skill_ids) {where("(array_remove(skill_ids, NULL) <> '{}') and (icount(array_remove(skill_ids, NULL) - ARRAY[?]) = 0)", skill_ids)}
  #scope :by_any_skills, ->(skill_ids) {where("icount(ARRAY[?] & skill_ids) > 0", skill_ids)}
  scope :by_wage, -> {order('wage desc')}
  scope :active, -> {where("active_until > ?", Date.today)}

  def skills
    Skill.where(id: self.skill_ids)
  end

  def best_candidates
    skills = self.skill_ids.compact
    skills = [0] if !skills || skills.empty? 
    Candidate.by_skills(skills).active.by_salary
  end

  def other_candidates
    skills = self.skill_ids.compact
    skills = [0] if !skills || skills.empty? 
    Candidate.active.
      select("candidates.*, count(skills.id) common_skill_count, string_agg(skills.name, ', ') skill_names").
      joins("inner join skills on skills.id = ANY(skill_ids & ARRAY#{skills})").
      group('candidates.id').having("count(skills.id) between 1 and #{skills.count-1}").order('count(skills.id) desc').by_salary
  end

  def validity= period
    @validity = period
    q = period.match(/(\d*).(days|day|week|weeks|month|months)/).captures
    self.active_until = Date.today + q[0].to_i.send(q[1])
  end

  def validity
    @validity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  inherit_resources

protected
  def candidate_params
    params.require(:candidate).permit(:name, :salary, :is_active, :contacts, skill_ids: [], new_skills: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
    @candidates = Candidate.by_skill(@skill.id)
    @vacancies = Vacancy.by_skill(@skill.id)
  end

  def search
    @skills = Skill.like_name(params[:query])
    render json: @skills.map{|s| {name: s.name, id: s.id}}
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  inherit_resources

protected
  def vacancy_params
    if action_name == 'create'
      params.require(:vacancy).permit(:name, :wage, :contacts, :validity, skill_ids: [], new_skills: [])
    else
      params.require(:vacancy).permit(:name, :wage, :contacts, :active_until, skill_ids: [], new_skills: [])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
  def vacancy_periods
    periods = []
    periods += (1..6).map {|d| ["#{d} #{Russian::p(d, 'день', 'дня', 'дней')}", "#{d}.day"]}
    periods += (1..3).map {|d| ["#{d} #{Russian::p(d, 'неделя', 'недели', 'недель')}", "#{d}.week"]}
    periods += (1..2).map {|d| ["#{d} #{Russian::p(d, 'месяц', 'месяца', 'месяцев')}", "#{d}.month"]}
    periods
  end
end

app/views/candidates/_form.html.haml
%h4= resource.new_record? ? 'Новый соискатель' : 'Редактирование соискателя'
= form_for resource, html: {role: :form} do |f|
  .row
    .col-md-5
      - if resource.errors.any?
        .alert.alert-danger(role=alert)
          %button.close{type: 'button', data: {dismiss: 'alert'}} ×
          %ul
            - resource.errors.full_messages.each do |msg|
              %li= msg  
        
      .form-group.form-group-sm
        = f.label :name, 'Имя'
        = f.text_field :name, class: 'form-control input-sm', placeholder: 'Имя соискателя (Фамилия Имя Отчество)'
      .form-group.form-group-sm
        = f.label :contacts, 'Контакты'
        = f.text_field :contacts, class: 'form-control input-sm', placeholder: 'Контакты (телефон или e-mail)'
      .row
        .form-group.form-group-sm.col-xs-5
          = f.label :salary, 'Зарплата (руб)'
          = f.number_field :salary, class: 'form-control input-sm', placeholder: 'Желаемая зарплата'
      .row
        .form-group.form-group-sm.col-xs-5
          .checkbox
            %label
              = f.check_box :is_active
              Резюме активно           
      .row
        .col-xs-12
          = link_to 'Отмена', candidates_path, class: 'button btn btn-default btn-sm', role: 'button'
          = f.submit 'Сохранить', class: 'btn btn-primary btn-sm'


    .col-md-3
      .panel.panel-default
        .panel-heading
          Навыки
        .panel-body#skills_manager
          .input-group.input-xs
            = text_field_tag :skill_name, '', class: 'form-control input-sm', autocomplete: 'off'
            %span.input-group-btn
              %button.btn.btn-success.btn-sm.btn-add-skill-candidate
                %span.glyphicon.glyphicon-plus
          = hidden_field_tag :selected_skill
          
          %hr
          %table.table.table-condensed
            = hidden_field_tag 'candidate[skill_ids][]', ''
            - resource.skills.each do |skill|
              %tr
                %td
                  = hidden_field_tag 'candidate[skill_ids][]', skill.id
                  = skill.name
                %td
                  = link_to '#', class: 'btn btn-xs btn-danger btn-remove-skill' do
                    %span.glyphicon.glyphicon-remove   
            - if resource.new_skills && resource.new_skills.any?  
              - resource.new_skills.each do |skill|
                %tr
                  %td
                    = hidden_field_tag 'candidate[new_skills][]', skill
                    = skill
                  %td
                    = link_to '#', class: 'btn btn-xs btn-danger btn-remove-skill' do
                      %span.glyphicon.glyphicon-remove    


:javascript
  $('#skill_name').typeahead({
    'ajax': '/skills/search',
    onSelect: function(item) {
      $('#skills_manager input#selected_skill').val(item.value)
    }
  });      

app/views/candidates/edit.html.haml
= render 'form'

app/views/candidates/index.html.haml
%h4 Кандидаты

.navbar.navbar-default
  .container-fluid
    = link_to 'Добавить', new_candidate_path, class: 'btn btn-xs btn-primary navbar-btn'

- if collection.any?
  %table.table.table-hover
    %thead
      %tr
        %th #
        %th Наименование
        %th Активно
        %th
    %tbody.data_table
      - collection.each do |candidate|
        %tr        
          %td= candidate.id
          %td= link_to candidate.name, candidate
          %td= candidate.is_active ? 'Да' : 'Нет'
          %td
            = link_to edit_candidate_path(candidate), class: 'btn btn-xs btn-success' do
              %span.glyphicon.glyphicon-pencil      
            = link_to candidate_path(candidate), class: 'btn btn-xs btn-danger', method: :delete do
              %span.glyphicon.glyphicon-remove                  

app/views/candidates/new.html.haml
= render 'form'

app/views/candidates/show.html.haml
%h4= resource.name
%h6= resource.contacts
%hr
%strong Навыки:
= resource.skills.map {|skill| link_to(skill.name, skill)}.join(', ').html_safe
%br
%strong Желаемая зарплата:
= number_to_currency(resource.salary)
%br
%strong= resource.is_active ? 'Резюме активно' : 'Резюме не активно'

%hr
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        Лучшие вакансии
      .panel-body
        %ul
          - resource.best_vacancies.each do |v|
            %li
              = link_to v.name, v
              = "(#{number_to_currency(v.wage)})"


  .col-md-6
    .panel.panel-default
      .panel-heading
        Другие вакансии
      .panel-body
        %ul
          - resource.other_vacancies.each do |c|
            %li
              = link_to c.name, c
              = "(#{c.skill_names} - #{number_to_currency(c.wage)})"

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Кадровое агенство
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-header
          = link_to 'Кадровое агенство', root_path, class: 'navbar-brand'

    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          %ul.nav.nav-sidebar
            %li{class: ('active' if controller_name == 'vacancies')}
              = link_to 'Вакансии', vacancies_path
            %li{class: ('active' if controller_name == 'candidates')}
              = link_to 'Кандидаты', candidates_path
            %li{class: ('active' if controller_name == 'skills')}
              = link_to 'Навыки', skills_path

        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = yield

app/views/skills/index.html.haml
%h4 Навыки

- if @skills.any?
  %table.table.table-hover
    %thead
      %tr
        %th #
        %th Наименование
    %tbody.data_table
      - @skills.each do |skill|
        %tr        
          %td= skill.id
          %td= link_to skill.name, skill

app/views/skills/show.html.haml
%h4= @skill.name

.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        Вакансии
      .panel-body
        %ul
          - @vacancies.each do |v|
            %li= link_to v.name, v


  .col-md-6
    .panel.panel-default
      .panel-heading
        Кандидаты
      .panel-body
        %ul
          - @candidates.each do |c|
            %li= link_to c.name, c

app/views/vacancies/_form.html.haml
%h4= resource.new_record? ? 'Новая вакансия' : 'Редактирование вакансии'
= form_for resource, html: {role: :form} do |f|
  .row
    .col-md-5
      - if resource.errors.any?
        .alert.alert-danger(role=alert)
          %button.close{type: 'button', data: {dismiss: 'alert'}} ×
          %ul
            - resource.errors.full_messages.each do |msg|
              %li= msg  
        
      .form-group.form-group-sm
        = f.label :name, 'Наименование'
        = f.text_field :name, class: 'form-control input-sm', placeholder: 'Наименование вакансии'
      .form-group.form-group-sm
        = f.label :contacts, 'Контакты'
        = f.text_field :contacts, class: 'form-control input-sm', placeholder: 'В свободном формате'
      .row
        .form-group.form-group-sm.col-xs-5
          = f.label :wage, 'Зарплата (руб)'
          = f.number_field :wage, class: 'form-control input-sm', placeholder: 'Зарплата'
        - if resource.new_record?
          .form-group.form-group-sm.col-xs-5
            = f.label :validity, 'Период действия'
            = f.select :validity, options_for_select(vacancy_periods, resource.validity), {}, {class: 'form-control input-sm'}
        - else
          .form-group.form-group-sm.col-xs-5
            = f.label :active_until, 'Дата'
            .input-group.date#active_until_picker
              = f.text_field :active_until, value: resource.active_until.try(:strftime, '%d.%m.%Y'), class: 'form-control'
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
      .row
        .col-xs-12
          = link_to 'Отмена', vacancies_path, class: 'button btn btn-default btn-sm', role: 'button'
          = f.submit 'Сохранить', class: 'btn btn-primary btn-sm'

    .col-md-3
      .panel.panel-default
        .panel-heading
          Навыки
        .panel-body#skills_manager
          .input-group.input-xs
            = text_field_tag :skill_name, '', class: 'form-control input-sm', autocomplete: 'off'
            %span.input-group-btn
              %button.btn.btn-success.btn-sm.btn-add-skill-vacancy
                %span.glyphicon.glyphicon-plus
          = hidden_field_tag :selected_skill
          
          %hr
          %table.table.table-condensed
            = hidden_field_tag 'vacancy[skill_ids][]', ''
            - resource.skills.each do |skill|
              %tr
                %td
                  = hidden_field_tag 'vacancy[skill_ids][]', skill.id
                  = skill.name
                %td
                  = link_to '#', class: 'btn btn-xs btn-danger btn-remove-skill' do
                    %span.glyphicon.glyphicon-remove   
            - if resource.new_skills && resource.new_skills.any?  
              - resource.new_skills.each do |skill|
                %tr
                  %td
                    = hidden_field_tag 'vacancy[new_skills][]', skill
                    = skill
                  %td
                    = link_to '#', class: 'btn btn-xs btn-danger btn-remove-skill' do
                      %span.glyphicon.glyphicon-remove    


      - unless resource.new_record?
        :javascript
          $('#active_until_picker').datetimepicker({
            locale: 'ru',
            format: 'DD.MM.YYYY'
          });

:javascript
  $('#skill_name').typeahead({
    'ajax': '/skills/search',
    onSelect: function(item) {
      $('#skills_manager input#selected_skill').val(item.value)
    }
  });      

app/views/vacancies/edit.html.haml
= render 'form'

app/views/vacancies/index.html.haml
%h4 Вакансии

.navbar.navbar-default
  .container-fluid
    = link_to 'Добавить', new_vacancy_path, class: 'btn btn-xs btn-primary navbar-btn'

- if collection.any?
  %table.table.table-hover
    %thead
      %tr
        %th #
        %th Наименование
        %th Действует до
        %th
    %tbody.data_table
      - collection.each do |vacancy|
        %tr        
          %td= vacancy.id
          %td= link_to vacancy.name, vacancy
          %td= l vacancy.active_until
          %td
            = link_to edit_vacancy_path(vacancy), class: 'btn btn-xs btn-success' do
              %span.glyphicon.glyphicon-pencil      
            = link_to vacancy_path(vacancy), class: 'btn btn-xs btn-danger', method: :delete do
              %span.glyphicon.glyphicon-remove        

app/views/vacancies/new.html.haml
= render 'form'

app/views/vacancies/show.html.haml
%h4= resource.name
%h6= resource.contacts
%hr
%strong Необходимые навыки:
= resource.skills.map {|skill| link_to(skill.name, skill)}.join(', ').html_safe
%br
%strong Зарплата:
= number_to_currency(resource.wage)
%br
%strong 
  Активна еще 
  = distance_of_time_in_words(Date.today, resource.active_until)
%hr
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        Лучшие кандидаты
      .panel-body
        %ul
          - resource.best_candidates.each do |c|
            %li
              = link_to c.name, c
              = "(#{number_to_currency(c.salary)})"


  .col-md-6
    .panel.panel-default
      .panel-heading
        Другие кандидаты
      .panel-body
        %ul
          - resource.other_candidates.each do |c|
            %li
              = link_to c.name, c
              = "(#{c.skill_names} - #{number_to_currency(c.salary)})"